# Generated by Django 3.0.4 on 2020-03-20 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20200315_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=30)),
                ('choice2', models.CharField(max_length=30)),
                ('choice3', models.CharField(max_length=30)),
                ('choice4', models.CharField(max_length=30)),
                ('correct_answer', models.CharField(max_length=30)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Quiz')),
            ],
        ),
    ]
