# Generated by Django 3.0.4 on 2020-03-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='question', max_length=200),
            preserve_default=False,
        ),
    ]
