# Generated by Django 3.0.4 on 2020-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_question_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks_correct',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='marks_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='marks_not_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
